Repository Activiti/example-runtime-bundle, pull requests merged in 2018-11, with the labels that each got.

#43 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.75
  pom.xml
Labels: updatebot

#45 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.76
  pom.xml
Labels: updatebot

#46 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.77
  pom.xml
Labels: updatebot

#47 Add new process definitions for Acceptance Test Refactoring
  src/main/resources/processes/Process Information.bpmn20.xml
  src/main/resources/processes/Process with Generic  BPMN Task.bpmn20.xml
Labels: in progress

#48 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.81
  pom.xml
Labels: in progress, updatebot

#49 applying cloud dep upgrade to master
  pom.xml
Labels: in progress

#51 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.90
  .travis.yml
  pom.xml
Labels: in progress, updatebot

#52 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.91
  pom.xml
Labels: in progress, updatebot

#53 remove bean overriding
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: in progress
